language: ruby
cache: bundler
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
    condition: "-d build"
install:
  - git fetch origin gh-pages:gh-pages
  - bundle install
script: bin/travis.sh
